

# This file was *autogenerated* from the file champernowne.sage
from sage.all_cmdline import *   # import sage library

_sage_const_20000 = Integer(20000); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_1200 = Integer(1200)
fi = open("champ_base_ten.txt", "w+")

rten = RealField(_sage_const_20000 )
b = rten(_sage_const_10 )

C_b = sum(rten(n)/(b**(rten(n) + sum(floor(rten(log(k+_sage_const_1 , b))) for k in range(_sage_const_1 , n)))) for n in range(_sage_const_1 , _sage_const_1200 ))
fi.write(str(C_b))


