

# This file was *autogenerated* from the file type_1d_big_prec.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_99999 = Integer(99999); _sage_const_75 = Integer(75); _sage_const_3000000 = Integer(3000000); _sage_const_3500000 = Integer(3500000); _sage_const_p1 = RealNumber('.1'); _sage_const_60 = Integer(60)
import time
def distance_from_int(y, rbig):
    x = rbig(abs(y)) 
    from_below = x - rbig(floor(x)) 
    from_above = rbig(ceil(x)) - x 
    return rbig(min(rbig(from_below), rbig(from_above)))


def test_for_bad_integers(alpha, epsilon, upper_bound, c_bound, eta):
    smallest_c = _sage_const_10 
    smallest_c_int = _sage_const_0 
    bad_ints_and_LHS = []
    for m in range(_sage_const_1 , upper_bound):
        d = distance_from_int(m*alpha)
        lhs = d*m**(eta + epsilon)
        #print("m = " + str(m))
        #print(str(lhs))
        if lhs < smallest_c:
            smallest_c = lhs
            smallest_c_int = m
        if lhs < c_bound:
            #print("at m = " + str(m) + " LHS = " + str(lhs))
            bad_ints_and_LHS.append([m, lhs]) 
    return [smallest_c.n(), smallest_c_int, bad_ints_and_LHS]


rbig = RealField(_sage_const_99999 )
fi = open("champ_base_ten.txt", "r")
champ_string = fi.read()
num = "champernowne constant"
rnum = rbig(champ_string)

#num = pi
#rnum = rbig(num)


#p = 19
#trace = 1
#num = arccos(trace/(2*sqrt(p)))
#rnum = rbig(num)
step_size = _sage_const_75 
start_index = _sage_const_3000000 
upperbound = _sage_const_3500000 
c_bound = _sage_const_p1 
eta = _sage_const_1 
epsilon = _sage_const_p1 
local_time = time.asctime(time.localtime(time.time()))
print("started at " + str(local_time))
t1 = time.time()
data_pts = []
for m in range(start_index, upperbound, step_size):
    d = distance_from_int(m*rnum, rbig)
    #print(str(log(d, m)))
    pt = [m, log(d, rbig(m**(eta+epsilon)))]
    data_pts.append(pt)
plt = plot(points(data_pts))
t2 = time.time()
#plt.save("log_plot_for_trace_" + str(trace) + "_p_"+ str(p) + "_eta_" + str(eta) + "skipping_" + str(step_size) + ".png")
plt.save("log_plot_for_" + str(num) + "_eta_" + str(eta) + "skipping_" + str(step_size) + ".png")
print("took "  + str( (t2 - t1)/_sage_const_60 ) + " minutes")

